version: "3.9"

services:
  sadtalker:
    image: wawa9000/sadtalker
    container_name: sadtalker
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "10364:10364"
    volumes:
      - ./checkpoints:/SadTalker/checkpoints
      - ./gfpgan/weights:/SadTalker/gfpgan/weights
      - ./results:/SadTalker/results
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
