version: "3.9"

services:
  sadtalker-api:
    build: .
    container_name: sadtalker-api
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "10364:8000"  # ホスト10364 → コンテナ8000
    volumes:
      - ./:/SadTalker_copy  # プロジェクト全体をマウント
    stdin_open: true
    tty: true
